# Configuration options
CAPTURE_SCREENSHOTS = True
BLUR_SCREENSHOTS = True

# S3 configuration
S3_BUCKET_NAME = 'myactivitytrackerbyvinove'
AWS_ACCESS_KEY_ID = 'AKIA6ODU3XBWQ2AUZK4E'
AWS_SECRET_ACCESS_KEY = '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'