# Configuration options
CAPTURE_SCREENSHOTS = True
BLUR_SCREENSHOTS = True
SCREENSHOT_INTERVAL = 300  # 5 minutes
SCREENSHOT_QUALITY = 50
MAX_LOCAL_STORAGE_DAYS = 1
SCREENSHOT_ARCHIVE_DIR = "archived_screenshots"
LOW_BATTERY_THRESHOLD = 20